# Generated by Django 4.2.4 on 2023-08-25 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Casilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_casilla', models.IntegerField(verbose_name='Numero Casilla:')),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre Ruta:')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo Ruta:')),
                ('coordenadas', models.CharField(max_length=50, verbose_name='Coordenada Ruta:')),
            ],
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=50, verbose_name='Categoria Vehiculo')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Monto:')),
                ('fecha_modificacion', models.DateField(verbose_name='Fecha Modificacion:')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre:')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido:')),
                ('direccion', models.CharField(max_length=50, verbose_name='Direccion:')),
                ('email', models.EmailField(max_length=254, verbose_name='Email:')),
                ('tipo_documento', models.CharField(max_length=50, verbose_name='Tipo Documento:')),
                ('numero_documento', models.CharField(max_length=50, verbose_name='Numero Documento:')),
                ('password', models.CharField(max_length=50, verbose_name='Password:')),
                ('permisos', models.BooleanField(verbose_name='Permiso:')),
            ],
        ),
        migrations.CreateModel(
            name='TurnoTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fh_inicio', models.DateTimeField(verbose_name='Fecha y Hora Incio:')),
                ('fh_fin', models.DateTimeField(verbose_name='Fecha y Hora Final:')),
                ('sentido_cobro', models.CharField(max_length=100, verbose_name='Sentido de Cobro:')),
                ('monto_inicial', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Monto Inicial:')),
                ('enlace_reporte', models.CharField(max_length=50, verbose_name='Enlace Reporte:')),
                ('id_casilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peajeApp.casilla')),
                ('id_operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peajeApp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroCobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fh_emision', models.DateTimeField(verbose_name='Fecha y Hora Emision:')),
                ('id_tarifa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peajeApp.tarifa')),
                ('id_turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peajeApp.turnotrabajo')),
            ],
        ),
        migrations.CreateModel(
            name='Estacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_estacion', models.IntegerField(verbose_name='Numero Estacion:')),
                ('km_ruta', models.IntegerField(verbose_name='KM Ruta:')),
                ('id_ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peajeApp.ruta')),
            ],
        ),
        migrations.AddField(
            model_name='casilla',
            name='id_estacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peajeApp.estacion'),
        ),
    ]
