# Generated by Django 4.2.4 on 2023-08-28 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peajeApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casilla',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado:'),
        ),
        migrations.AddField(
            model_name='turnotrabajo',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado:'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='tipo',
            field=models.CharField(choices=[('Nacional', 'Nacional'), ('Provincial', 'Provincial'), ('Municipal', 'Muncipal')], max_length=50, verbose_name='Tipo Ruta:'),
        ),
        migrations.AlterField(
            model_name='tarifa',
            name='categoria',
            field=models.CharField(choices=[('motocicleta', 'Motocicleta'), ('automoviles', 'Automóviles'), ('2_ejes_duales', '2 Ejes con Ruedas Duales o Altura Mayor a 2.10m'), ('3_4_ejes', '3 o 4 Ejes, Sin Ruedas Duales y Altura Menor a 2.10m'), ('5_6_ejes', '5 o 6 Ejes'), ('mas_de_6_ejes', 'Más de 6 Ejes')], max_length=50, verbose_name='Categoria Vehiculo'),
        ),
    ]
