# Generated by Django 4.2.4 on 2023-08-28 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peajeApp', '0002_casilla_estado_turnotrabajo_estado_alter_ruta_tipo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turnotrabajo',
            old_name='id_operador',
            new_name='id_usuario',
        ),
    ]
