# Generated by Django 4.2.4 on 2023-08-31 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peajeApp', '0003_rename_id_operador_turnotrabajo_id_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casilla',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Abierto:'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='permisos',
            field=models.BooleanField(verbose_name='Admin:'),
        ),
    ]
