# Generated by Django 4.2.4 on 2023-09-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peajeApp', '0004_alter_casilla_estado_alter_usuario_permisos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casilla',
            old_name='id_estacion',
            new_name='estacion',
        ),
        migrations.RenameField(
            model_name='estacion',
            old_name='id_ruta',
            new_name='ruta',
        ),
        migrations.RenameField(
            model_name='registrocobro',
            old_name='id_tarifa',
            new_name='tarifa',
        ),
        migrations.RenameField(
            model_name='registrocobro',
            old_name='id_turno',
            new_name='turno',
        ),
        migrations.RenameField(
            model_name='turnotrabajo',
            old_name='id_casilla',
            new_name='casilla',
        ),
        migrations.RenameField(
            model_name='turnotrabajo',
            old_name='id_usuario',
            new_name='usuario',
        ),
        migrations.AddField(
            model_name='registrocobro',
            name='patente',
            field=models.CharField(default='NULL', max_length=24, verbose_name='Patente:'),
        ),
    ]
