# Generated by Django 4.2.4 on 2023-09-02 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peajeApp', '0005_rename_id_estacion_casilla_estacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='tipo',
            field=models.CharField(choices=[('Nacional', 'Nacional'), ('Provincial', 'Provincial')], max_length=50, verbose_name='Tipo Ruta:'),
        ),
    ]
