# Generated by Django 4.2.4 on 2023-09-04 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peajeApp', '0006_alter_ruta_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turnotrabajo',
            name='enlace_reporte',
            field=models.CharField(default='NULL', max_length=50, verbose_name='Enlace Reporte:'),
        ),
    ]
