# Generated by Django 4.2.4 on 2023-09-04 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peajeApp', '0007_alter_turnotrabajo_enlace_reporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turnotrabajo',
            name='monto_inicial',
            field=models.IntegerField(verbose_name='Monto Inicial:'),
        ),
    ]
