# Generated by Django 4.2.4 on 2023-09-04 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peajeApp', '0008_alter_turnotrabajo_monto_inicial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turnotrabajo',
            name='monto_inicial',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Monto Inicial:'),
        ),
    ]
